// Plant database with common house plants, vegetables, fruits, herbs, and outdoor plants

export interface PlantTypeInfo {
  id: string;
  name: string;
  scientificName: string;
  category: 'houseplant' | 'vegetable' | 'fruit' | 'herb' | 'flower' | 'tree' | 'succulent';
  careDifficulty: 'easy' | 'moderate' | 'difficult';
  light: 'low' | 'medium' | 'high';
  water: 'low' | 'medium' | 'high';
  tempMin: number;
  tempMax: number;
  humidityMin: number;
  humidityMax: number;
  soilMoistureMin: number; // in percentage
  soilMoistureMax: number; // in percentage
  description: string;
  imageUrl?: string;
}

export const plantCategories = [
  { id: 'houseplant', name: 'House Plants' },
  { id: 'vegetable', name: 'Vegetables' },
  { id: 'fruit', name: 'Fruits' },
  { id: 'herb', name: 'Herbs' },
  { id: 'flower', name: 'Flowers' },
  { id: 'tree', name: 'Trees' },
  { id: 'succulent', name: 'Succulents & Cacti' }
];

export const plantTypes: PlantTypeInfo[] = [
  // House Plants
  {
    id: 'pothos',
    name: 'Pothos',
    scientificName: 'Epipremnum aureum',
    category: 'houseplant',
    careDifficulty: 'easy',
    light: 'low',
    water: 'low',
    tempMin: 15,
    tempMax: 24,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 20,
    soilMoistureMax: 40,
    description: 'A popular trailing houseplant with heart-shaped leaves, known for being very easy to care for and propagate.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Epipremnum_aureum_31082012.jpg',
  },
  {
    id: 'snake-plant',
    name: 'Snake Plant',
    scientificName: 'Dracaena trifasciata',
    category: 'houseplant',
    careDifficulty: 'easy',
    light: 'low',
    water: 'low',
    tempMin: 18,
    tempMax: 27,
    humidityMin: 30,
    humidityMax: 50,
    soilMoistureMin: 15,
    soilMoistureMax: 30,
    description: 'An extremely hardy plant with tall, rigid, sword-like leaves. Perfect for beginners and purifies air efficiently.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg',
  },
  {
    id: 'peace-lily',
    name: 'Peace Lily',
    scientificName: 'Spathiphyllum',
    category: 'houseplant',
    careDifficulty: 'easy',
    light: 'low',
    water: 'medium',
    tempMin: 18,
    tempMax: 30,
    humidityMin: 50,
    humidityMax: 70,
    soilMoistureMin: 30,
    soilMoistureMax: 50,
    description: 'Elegant plant with glossy leaves and white flowers (actually modified leaves). Good air purifier and humidity indicator.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Spathiphyllum_cochlearispathum_RTBG.jpg',
  },
  {
    id: 'spider-plant',
    name: 'Spider Plant',
    scientificName: 'Chlorophytum comosum',
    category: 'houseplant',
    careDifficulty: 'easy',
    light: 'medium',
    water: 'medium',
    tempMin: 13,
    tempMax: 27,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 30,
    soilMoistureMax: 50,
    description: 'Fast-growing plant with arching leaves and baby plantlets that dangle from stems like spiders on a web.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Chlorophytum_comosum_17-08-2009_16-55-49.JPG',
  },
  {
    id: 'monstera',
    name: 'Swiss Cheese Plant',
    scientificName: 'Monstera deliciosa',
    category: 'houseplant',
    careDifficulty: 'moderate',
    light: 'medium',
    water: 'medium',
    tempMin: 18,
    tempMax: 30,
    humidityMin: 50,
    humidityMax: 70,
    soilMoistureMin: 30,
    soilMoistureMax: 50,
    description: 'Tropical plant famous for its large, glossy leaves with distinctive splits and holes.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/Monstera_deliciosa_R1.jpg',
  },
  {
    id: 'fiddle-leaf-fig',
    name: 'Fiddle Leaf Fig',
    scientificName: 'Ficus lyrata',
    category: 'houseplant',
    careDifficulty: 'difficult',
    light: 'high',
    water: 'medium',
    tempMin: 18,
    tempMax: 30,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 30,
    soilMoistureMax: 50,
    description: 'Popular houseplant with large, violin-shaped leaves. Beautiful but can be temperamental.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/58/Ficus_lyrata.jpg',
  },
  
  // Vegetables
  {
    id: 'tomato',
    name: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    category: 'vegetable',
    careDifficulty: 'moderate',
    light: 'high',
    water: 'medium',
    tempMin: 18,
    tempMax: 30,
    humidityMin: 40,
    humidityMax: 70,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Popular garden vegetable with juicy red fruits. Comes in many varieties from cherry to beefsteak.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/89/Tomato_je.jpg',
  },
  {
    id: 'lettuce',
    name: 'Lettuce',
    scientificName: 'Lactuca sativa',
    category: 'vegetable',
    careDifficulty: 'easy',
    light: 'medium',
    water: 'medium',
    tempMin: 10,
    tempMax: 24,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Quick-growing leafy green that is perfect for beginners. Harvest outer leaves for continuous growth.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/13/Iceberg_lettuce_8253.jpg',
  },
  {
    id: 'bell-pepper',
    name: 'Bell Pepper',
    scientificName: 'Capsicum annuum',
    category: 'vegetable',
    careDifficulty: 'moderate',
    light: 'high',
    water: 'medium',
    tempMin: 18,
    tempMax: 32,
    humidityMin: 40,
    humidityMax: 70,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Sweet, crunchy peppers that come in various colors as they ripen, from green to red, yellow, or orange.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Bell_pepper_overview.jpg',
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    scientificName: 'Cucumis sativus',
    category: 'vegetable',
    careDifficulty: 'moderate',
    light: 'high',
    water: 'high',
    tempMin: 18,
    tempMax: 30,
    humidityMin: 50,
    humidityMax: 70,
    soilMoistureMin: 50,
    soilMoistureMax: 70,
    description: 'Refreshing summer vegetable with sprawling vines that can be grown vertically to save space.',
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    scientificName: 'Cucurbita pepo',
    category: 'vegetable',
    careDifficulty: 'easy',
    light: 'high',
    water: 'medium',
    tempMin: 18,
    tempMax: 30,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Productive summer squash that provides abundant harvests. Pick when small for best flavor.',
  },
  
  // Fruits
  {
    id: 'strawberry',
    name: 'Strawberry',
    scientificName: 'Fragaria × ananassa',
    category: 'fruit',
    careDifficulty: 'easy',
    light: 'high',
    water: 'medium',
    tempMin: 15,
    tempMax: 26,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Sweet, red berries that grow on compact plants. Perfect for containers or hanging baskets.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/64/Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single.jpg',
  },
  {
    id: 'lemon',
    name: 'Lemon',
    scientificName: 'Citrus limon',
    category: 'fruit',
    careDifficulty: 'moderate',
    light: 'high',
    water: 'medium',
    tempMin: 13,
    tempMax: 30,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 30,
    soilMoistureMax: 50,
    description: 'Fragrant citrus tree with bright yellow fruits. Dwarf varieties work well in containers.',
  },
  {
    id: 'blueberry',
    name: 'Blueberry',
    scientificName: 'Vaccinium corymbosum',
    category: 'fruit',
    careDifficulty: 'moderate',
    light: 'high',
    water: 'medium',
    tempMin: 10,
    tempMax: 26,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Sweet blue berries on bushes that offer ornamental value with fall foliage. Needs acidic soil.',
  },
  {
    id: 'avocado',
    name: 'Avocado',
    scientificName: 'Persea americana',
    category: 'fruit',
    careDifficulty: 'difficult',
    light: 'high',
    water: 'medium',
    tempMin: 18,
    tempMax: 30,
    humidityMin: 40,
    humidityMax: 70,
    soilMoistureMin: 30,
    soilMoistureMax: 50,
    description: 'Tropical tree with creamy green fruits. Can be grown from a pit as a houseplant but rarely fruits indoors.',
  },
  {
    id: 'apple',
    name: 'Apple',
    scientificName: 'Malus domestica',
    category: 'fruit',
    careDifficulty: 'moderate',
    light: 'high',
    water: 'medium',
    tempMin: 7,
    tempMax: 26,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Classic fruit tree with many varieties. Dwarf types can be grown in small spaces or containers.',
  },
  
  // Herbs
  {
    id: 'basil',
    name: 'Basil',
    scientificName: 'Ocimum basilicum',
    category: 'herb',
    careDifficulty: 'easy',
    light: 'high',
    water: 'medium',
    tempMin: 18,
    tempMax: 30,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Aromatic herb with bright green leaves, essential for Italian cooking. Pinch flower buds to encourage leafy growth.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/90/Basil-Basilico-Ocimum_basilicum-albahaca.jpg',
  },
  {
    id: 'mint',
    name: 'Mint',
    scientificName: 'Mentha',
    category: 'herb',
    careDifficulty: 'easy',
    light: 'medium',
    water: 'high',
    tempMin: 15,
    tempMax: 27,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 50,
    soilMoistureMax: 70,
    description: 'Vigorous herb with refreshing fragrance. Best grown in containers as it spreads aggressively.',
  },
  {
    id: 'rosemary',
    name: 'Rosemary',
    scientificName: 'Salvia rosmarinus',
    category: 'herb',
    careDifficulty: 'moderate',
    light: 'high',
    water: 'low',
    tempMin: 10,
    tempMax: 27,
    humidityMin: 30,
    humidityMax: 50,
    soilMoistureMin: 20,
    soilMoistureMax: 40,
    description: 'Fragrant Mediterranean herb with needle-like leaves. Enjoys dry conditions and good drainage.',
  },
  {
    id: 'cilantro',
    name: 'Cilantro',
    scientificName: 'Coriandrum sativum',
    category: 'herb',
    careDifficulty: 'easy',
    light: 'medium',
    water: 'medium',
    tempMin: 10,
    tempMax: 24,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Fast-growing herb with bright, citrusy flavor. Plant succession crops for continuous harvest.',
  },
  {
    id: 'thyme',
    name: 'Thyme',
    scientificName: 'Thymus vulgaris',
    category: 'herb',
    careDifficulty: 'easy',
    light: 'high',
    water: 'low',
    tempMin: 10,
    tempMax: 27,
    humidityMin: 30,
    humidityMax: 50,
    soilMoistureMin: 20,
    soilMoistureMax: 40,
    description: 'Low-growing herb with tiny, aromatic leaves. Drought tolerant and excellent for rock gardens.',
  },
  
  // Flowers
  {
    id: 'sunflower',
    name: 'Sunflower',
    scientificName: 'Helianthus annuus',
    category: 'flower',
    careDifficulty: 'easy',
    light: 'high',
    water: 'medium',
    tempMin: 18,
    tempMax: 32,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Iconic summer flower with large yellow blooms. Varieties range from dwarf to giant.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/A_sunflower.jpg',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    scientificName: 'Lavandula',
    category: 'flower',
    careDifficulty: 'moderate',
    light: 'high',
    water: 'low',
    tempMin: 15,
    tempMax: 30,
    humidityMin: 30,
    humidityMax: 50,
    soilMoistureMin: 20,
    soilMoistureMax: 40,
    description: 'Fragrant Mediterranean herb with purple flower spikes. Needs excellent drainage.',
  },
  {
    id: 'rose',
    name: 'Rose',
    scientificName: 'Rosa',
    category: 'flower',
    careDifficulty: 'moderate',
    light: 'high',
    water: 'medium',
    tempMin: 13,
    tempMax: 28,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Classic garden flower known for beautiful blooms and fragrance. Many varieties for different conditions.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/51/Small_Red_Rose.JPG',
  },
  {
    id: 'marigold',
    name: 'Marigold',
    scientificName: 'Tagetes',
    category: 'flower',
    careDifficulty: 'easy',
    light: 'high',
    water: 'medium',
    tempMin: 18,
    tempMax: 32,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 30,
    soilMoistureMax: 50,
    description: 'Cheerful flowers in orange, yellow, and red. Natural pest repellent in vegetable gardens.',
  },
  {
    id: 'tulip',
    name: 'Tulip',
    scientificName: 'Tulipa',
    category: 'flower',
    careDifficulty: 'moderate',
    light: 'medium',
    water: 'medium',
    tempMin: 5,
    tempMax: 21,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Spring-blooming bulbs in nearly every color. Plant in fall for spring blooms.',
  },
  
  // Trees
  {
    id: 'maple',
    name: 'Japanese Maple',
    scientificName: 'Acer palmatum',
    category: 'tree',
    careDifficulty: 'moderate',
    light: 'medium',
    water: 'medium',
    tempMin: 10,
    tempMax: 26,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 40,
    soilMoistureMax: 60,
    description: 'Ornamental tree with delicate, colorful foliage. Dwarf varieties work well in containers.',
  },
  {
    id: 'olive',
    name: 'Olive Tree',
    scientificName: 'Olea europaea',
    category: 'tree',
    careDifficulty: 'moderate',
    light: 'high',
    water: 'low',
    tempMin: 15,
    tempMax: 30,
    humidityMin: 30,
    humidityMax: 50,
    soilMoistureMin: 20,
    soilMoistureMax: 40,
    description: 'Mediterranean tree with silvery leaves. Can be grown as a patio plant in cooler climates.',
  },
  
  // Succulents
  {
    id: 'aloe-vera',
    name: 'Aloe Vera',
    scientificName: 'Aloe barbadensis miller',
    category: 'succulent',
    careDifficulty: 'easy',
    light: 'medium',
    water: 'low',
    tempMin: 16,
    tempMax: 27,
    humidityMin: 30,
    humidityMax: 50,
    soilMoistureMin: 15,
    soilMoistureMax: 30,
    description: 'Medicinal succulent with thick, gel-filled leaves. Great for beginners.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Aloe_vera_flower_inset.png',
  },
  {
    id: 'echeveria',
    name: 'Echeveria',
    scientificName: 'Echeveria',
    category: 'succulent',
    careDifficulty: 'easy',
    light: 'high',
    water: 'low',
    tempMin: 18,
    tempMax: 27,
    humidityMin: 30,
    humidityMax: 50,
    soilMoistureMin: 15,
    soilMoistureMax: 30,
    description: 'Rosette-forming succulent in many colors and variations. Perfect for dish gardens.',
  },
  {
    id: 'jade-plant',
    name: 'Jade Plant',
    scientificName: 'Crassula ovata',
    category: 'succulent',
    careDifficulty: 'easy',
    light: 'medium',
    water: 'low',
    tempMin: 18,
    tempMax: 27,
    humidityMin: 30,
    humidityMax: 50,
    soilMoistureMin: 15,
    soilMoistureMax: 30,
    description: 'Tree-like succulent with oval leaves. Often kept as a houseplant for good luck.',
  },
  {
    id: 'christmas-cactus',
    name: 'Christmas Cactus',
    scientificName: 'Schlumbergera',
    category: 'succulent',
    careDifficulty: 'easy',
    light: 'medium',
    water: 'medium',
    tempMin: 15,
    tempMax: 27,
    humidityMin: 40,
    humidityMax: 60,
    soilMoistureMin: 30,
    soilMoistureMax: 50,
    description: 'Tropical cactus with flat, segmented stems and colorful blooms around holiday time.',
  }
];

// Helper functions

// Get all plants
export function getAllPlants(): PlantTypeInfo[] {
  return plantTypes;
}

// Get plants by category
export function getPlantsByCategory(category: string): PlantTypeInfo[] {
  return plantTypes.filter(plant => plant.category === category);
}

// Get plant by ID
export function getPlantById(id: string): PlantTypeInfo | undefined {
  return plantTypes.find(plant => plant.id === id);
}

// Search plants by name
export function searchPlants(query: string): PlantTypeInfo[] {
  if (!query || query.trim() === '') return [];
  
  const normalizedQuery = query.toLowerCase().trim();
  
  return plantTypes.filter(plant => 
    plant.name.toLowerCase().includes(normalizedQuery) || 
    plant.scientificName.toLowerCase().includes(normalizedQuery)
  );
}